id = "jinja2-helm"
name = "Jinja2 Helm"
description = "Syntax highlighting for Jinja2-templated Helm/YAML files (Copier + Helmfile workflow)"
version = "0.1.0"
schema_version = 1
authors = ["Jean <jean@cleyrop.com>"]
repository = "https://github.com/cleyrop/zed-jinja2-helm"

[grammars.jinja]
repository = "https://github.com/cleyrop/tree-sitter-jinja"
commit = "6f6a28e54221e465a4a14179a1e65bd180dd760c"
path = "tree-sitter-jinja"
